BEGIN TRANSACTION;

DROP USER IF EXISTS traininguser;
CREATE USER traininguser ENCRYPTED PASSWORD 'trainingpassword' NOSUPERUSER NOCREATEDB NOCREATEROLE;

COMMIT TRANSACTION;

DROP DATABASE IF EXISTS spring_boot_project;
CREATE DATABASE spring_boot_project OWNER traininguser ENCODING 'UTF8';